import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupaProvider } from "@/context/SupaContext";
import Script from 'next/script'
import TrailField from "@/components/TrailField/TrailField"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SupaProvider >
          <TrailField />
          {children}
        </ SupaProvider>
        <Script src="https://accounts.google.com/gsi/client" 
                strategy="afterInteractive"
        ></Script>
      </body>
    </html>
  );
}
